title: IIIF Annotation Demo
description: ''
baseurl: '/annotate'
url: ''

github_username: mnyrop
social_username: mariinyrop

permalink: pretty
theme: jekyll-swiss
exclude: [Rakefile, Gemfile*, vendor, README.md, LICENSE]

collections:
  viewers:
    output: true

webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
